name: Docker CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker_cicd1:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/docker_cicd1:sha-${{ github.sha }}

  container-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Pull image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/docker_cicd1:latest

      - name: Run container
        run: docker run -d -p 5000:5000 --name test ${{ secrets.DOCKERHUB_USERNAME }}/docker_cicd1:latest

      - name: Wait for server
        run: sleep 5

      - name: Test endpoints
        run: |
          curl -f http://localhost:5000/
          curl -f http://localhost:5000/healthz | grep "ok"

      - name: Clean up
        run: docker rm -f test
